### ISSUE TITLE
ルートフォルダにファイルコピーしようとするとエラー

### ISSUE THREAD

**Issue by crftwr** [crftwr/cfiler#6]
ルートフォルダにファイルコピーしようとするとエラーが発生します。
ログは以下の通りでした。
コピー : From : C:/Apps/cfiler/readme.txt
: To : D:/readme.txt …
Debug: Traceback (most recent call last):
File ".\cfiler_mainwindow.py", line 3490, in copy_file
File ".\cfiler_filelist.py", line 423, in getCopyDst
File "c:/Python35/Lib\os.py", line 241, in makedirs
PermissionError: [WinError 5] アクセスが拒否されました。: 'D:/'
失敗
[WinError 5] アクセスが拒否されました。: 'D:/'
中断しました.

環境は、Windows7およびWindows10です。

**Comment by crftwr** [comment]
ver 2.46で修正されます。
